### ISSUE TITLE
Checkboxes?

### ISSUE THREAD

**Issue by purpetrator** [camelot-dev/camelot#163]
Is there any way to read data to see if a checkbox is checked or unchecked in a PDF?

**Comment by vinayak-mehta** [comment]
Depending on the page layout, it might be possible to increase the [line_scale](https://camelot-py.readthedocs.io/en/latest/user/advanced.html#detect-short-lines) so that the checkbox gets captured as a table cell (with the check mark inside it). If the checkbox occurs at the same location on multiple pages, you could assume that the indices for the corresponding cell will be the same for all of them (though it might make sense to manually verify it for some pages first).
