### ISSUE TITLE
Installation on linux with pip misses the python3-xlwt dependency

### ISSUE THREAD

**Issue by D-W-L** [camelot-dev/camelot#210]
The installation guide for "pip" only lists tk and ghostscript as external dependencies. On linux for excel export python3-xlwt is missing.

**Environment**
 - OS: linux debian 11 bullseye (sid at time of writing)
 - Python version: 3.9.0
 - Numpy version: 1.19.4
 - OpenCV version: 4.2.0
 - Ghostscript version: 9.53.3
 - Camelot version: 0.8.2

btw. Thank you very much for this nice tool!

**Comment by Arnie97** [comment]
That is an optional dependency for `pandas`. Pandas support a bunch of different I/O formats, and most of them requires optional external dependencies, e.g. `tables` for hdf, `tabulate` for markdown, `xlwt` for excel, `pyarrow` for feather, `pandas_gbq` for Google BigQuery and so many more. AFAIK these're not even documented in `pandas`' own docs. Maybe it's no big deal since `pandas` did provide a clear guidance for what should be installed when you try to aceess these file formats :-)
