### ISSUE TITLE
Found bug in codebase?

### ISSUE THREAD

**Issue by awa5114** [camelot-dev/camelot#243]
I think I might have found a bug in the codebase. I am using version 0.9.0 of `camelot-py` and the following line uses a strange order for the bounding box definition:

https://github.com/camelot-dev/camelot/blob/c647f573d89d45b87119554c76b4f8234ea63f25/camelot/parsers/stream.py#L307

The docstring in `text_in_bbox` specifies that a  `Tuple (x1, y1, x2, y2)`  should be passed. `(x1, y1)` is the lower left corner of the box and `x2, y2` is the upper right corner.

Could somebody please check whether this is in fact a bug? I believe it might be causing the `ZeroDivisionError` problem when using `table_regions`, since the `text_in_bbox` fails to return any text...

**Comment by vinayak-mehta** [comment]
The input strings that are passed in should be `x1,y1,x2,y2` where `(x1, y1)` -> top-left and `(x2, y2)` -> bottom-right. You can find more info in the section here: https://camelot-py.readthedocs.io/en/master/user/advanced.html#specify-table-areas This part of the codebase hasn't changed from 0.8.2 to 0.9.0 so that shouldn't be the issue.

**Comment by vinayak-mehta** [comment]
You can also check out usage in the test here: https://github.com/camelot-dev/camelot/blob/master/tests/test_common.py#L69
